### ISSUE TITLE
Running with several different seeds

### ISSUE THREAD

**Issue by avilella** [gymreklab/tulip#41]
Can I simulate reads from same input but given different seeds? Eg. Simulate 10 times for same starting input library/peakset.

**Comment by Pandaman-Ryan** [comment]
Yes, you can. We use the wall-clock time as the random seed. So you can simply run "Tulip" for 10 times for your input peakset.

**Comment by avilella** [comment]
Could you add this as a parameter so that it can be reproducibly reran with
the same seed again? Thanks in advance.

**Comment by Pandaman-Ryan** [comment]
Thank you so much for your suggestions. Our team needs some time to discuss it and find the best solution.

Randomization exists in every step of our simulation: shearing, pull-down, sequencing, etc. To add the feature you ask, we'll need to change and test multiple spots of our code.

We will get back to you in a week.

**Comment by avilella** [comment]
Thanks for your consideration

**Comment by Pandaman-Ryan** [comment]
Hi @avilella

We have added an option, "--seed", in the simreads module which allows you to specify a random seed. And if “--seed” is set as 0 or left blank, Tulip will use the wall clock time as the random seed. In either case, Tulip will print the random seed currently used, e.g. “Current random seed: 396587666”, so that you can replicate your experiments afterward.

Note: This random seed option works for both single-thread and multi-thread settings. In the multi-thread setting, the order of output sequences in the fastq file may be different in each run, because threads claim their jobs in an arbitrary manner during run-time. The total contents, however, stay the same in different runs.

You can download the latest version from our github (https://github.com/gymreklab/tulip.git) and compile Tulip from its source code. We will include this update in our next tarball release as well.

Thank you so much for your input and advice.

Cheers,
